In [1]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt

In [2]:
fn = "../OFC_data/v7_EC99_preprocessedDuringContinuous_6mA_Right_FreqBands.mat"
mat = loadmat(fn)

In [3]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'data'])

In [4]:
len(mat["data"][0][0])

19

In [5]:
mat["data"][0][0][0]

array([[16384]], dtype=uint16)

In [6]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Wed Aug  9 16:20:00 2023',
 '__version__': '1.0',
 '__globals__': [],
 'data': array([[(array([[16384]], dtype=uint16), array([[ 10,  16,  29,  30,  46,  69,  71,  72,  74,  75,  76,  77,  79,
                  82, 108]], dtype=uint8), array([[33]], dtype=uint8), array([[14]], dtype=uint8), array([[ 709703,  709868,  710032, ..., 4354320, 4354484, 4354649]],
               dtype=int32), array([[ 709656,  709821,  709985, ..., 4354273, 4354437, 4354602]],
               dtype=int32), array([[512]], dtype=uint16), array([[array(['ROF1'], dtype='<U4'), array(['ROF2'], dtype='<U4'),
                 array(['RH1'], dtype='<U3'), array(['RH2'], dtype='<U3'),
                 array(['RH3'], dtype='<U3'), array(['RH4'], dtype='<U3'),
                 array(['RC1'], dtype='<U3'), array(['RC2'], dtype='<U3'),
                 array(['RI1'], dtype='<U3'), array(['RI2'], dtype='<U3'),
                 array(['RI3'], dtype='<U3'), 

In [7]:
var_names = mat["data"].dtype.names

In [8]:
var_names

('Fs',
 'allRejectedChans',
 'artifactBufferAfter',
 'artifactBufferBefore',
 'artifactEnds',
 'artifactStarts',
 'dsFs',
 'finalVerifiedChanNames',
 'finalVerifiedRegions',
 'numVerifiedChans',
 'patientID',
 'plotStimEnd',
 'plotStimStart',
 'preprocessedStimData',
 'regionNames',
 'rejectionTimes',
 'removeOrReplace',
 'selectVerifiedAnatomy',
 'stimFreq')

In [9]:
dat = mat["data"][0][0]

In [10]:
dat[1]

array([[ 10,  16,  29,  30,  46,  69,  71,  72,  74,  75,  76,  77,  79,
         82, 108]], dtype=uint8)

In [11]:
dat[-1]

array([[100]], dtype=uint8)

In [12]:
dat[-2][0]

array([array(['ROF1'], dtype='<U4'),
       array(['RightOFCDepthElectrode1'], dtype='<U23'),
       array(['depth'], dtype='<U5'),
       array(['ctx_rh_G_rectus'], dtype='<U15')], dtype=object)

In [13]:
np.concatenate(dat[-2][0])

array(['ROF1', 'RightOFCDepthElectrode1', 'depth', 'ctx_rh_G_rectus'],
      dtype='<U23')

In [14]:
data = dat[-6]

In [26]:
np.squeeze(data_dict["preprocessedStimData"]) == data_dict["preprocessedStimData"]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

# Compare with v7.3 numbers

In [14]:
import h5py

In [15]:
v73fn = "../OFC_data/EC99_preprocessedDuringContinuous_6mA_Right_FreqBands.mat"
v73dat = h5py.File(v73fn, "r")

In [16]:
v73data = np.array(dat["preprocessedStimData"])

In [17]:
np.sum(data - v73data)

0.0

In [18]:
np.where(data != v73data)

(array([], dtype=int64), array([], dtype=int64))